import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { SidebarProvider } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/common/AppSidebar";
import { AppTopbar } from "@/components/common/AppTopbar";
import { ThemeProvider } from "@/components/common/ThemeProvider";
import "@/styles/globals.css";
import { ReactQueryProvider } from "@/components/common/ReactQueryProvider";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <ReactQueryProvider>
            <div className="flex flex-col h-screen">
              <div className="flex flex-1">
                <SidebarProvider>
                  <AppSidebar />
                  <div className="flex flex-col flex-1">
                    <AppTopbar />
                    <main className="flex-1 p-4">
                      {children}
                      <Toaster />
                    </main>
                  </div>
                </SidebarProvider>
              </div>
            </div>
          </ReactQueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
